language: python
python:
- '3.4'
install:
- pip install .
script: nosetests
deploy:
  provider: pypi
  user: jared.bunting
  password:
    secure: SrJio/n7v6WzLAcU4Y3LpQHlK/xwiZT0zRcZMywrGdbywwxAIfvlNG0bNs+3C+q58dlfl5dQmSQ+HgxQcZTt0Jb5/54DFVVdnBfBybAmR1C8Hgx0i5a0T7H9LUKRBRqg2EoIRznjEmsVEd2w4KcPMMehja19Qgiw9r6kmycO86U=
  allow_failure: false
  on:
    tags: true
    all_branches: true
    repo: peachjean/dnsfiles
