language: python
python:
- '3.4'
install:
- pip install .
script: nosetests
deploy:
  provider: pypi
  user: jared.bunting
  password:
    secure: hdSrfuFW47uWqWdiD9smJEQuhvCq4+ae90VX1mP7n5FtLoTcgSNsEM6sI1l3PaAqkX/fXX9heMqtYWL8wf3JF6PX3WYqeCwFID7Tl9hAYx2ECLywkajJ1tfyUCsEMJG8SE+rDwKjdPUf7sMQ9BRRbNJaq63vCM2+5hu3mU/qMyY=
  on:
    tags: true
    all_branches: true
    repo: peachjean/dnsfiles
