language: python
python:
- '3.4'
install:
- pip install .
script: nosetests
deploy:
  provider: pypi
  user: jared.bunting
  password:
    secure: eZZLKtK3y9V6eZfPbcslIgTLTLGdHRLY33XAyI+2/qQUNAYDodbBGBiYCAvvdX5EKAXDdVq87OlujtEQzycW6YHtxAdfGhAAAEG3bNh2QX1n+oj3Pr+XTlR4jpm+hEQg4PJ/PHozfVAhR9676A9jsKfrsgJWlv1E5X3L0TH4wfo=
  on:
    tags: true
    all_branches: true
    repo: peachjean/dnsfiles
