language: python
python:
- '3.4'
install:
- pip install .
script: nosetests
deploy:
  provider: pypi
  user: jared.bunting
  password:
    secure: "d+K+DLxSZW8wqI7LtZF5y3/uq+MXUgQh4FX6m9r4elSFYL1hfOODqJa7bDe39fbIg4HvZ2JwBLhetkog5WRtY5F+V24mNAFS18zVd7oOZ5UECzQp5YoNKzXZNuis87c6NTG4HWSla6TsuUJBB+6LWlRQ6pkEDF9UYzBgQGefx6w="
  allow_failure: false
  on:
    tags: true
    all_branches: true
    repo: peachjean/dnsfiles
